### ISSUE TITLE
Squid proxy with authentication

### ISSUE THREAD

**Issue by alter** [aiqinxuancai/DiscordProxyStart#4]
Hi, I've setup squid proxy in docker, with very simple configuration:
```
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic children 5
auth_param basic realm Squid Basic Authentication
auth_param basic credentialsttl 87600 hours
acl auth_users proxy_auth REQUIRED
http_access allow auth_users
http_port 3128
```

and docker-compose.yml:
```
version: "3"
services:
  proxy:
    image: ubuntu/squid
    ports:
      - "8080:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```

 /etc/squid/passwords generated htpasswd tool with md5 format.
 
 this proxy 100% works, b/c I can use it in linux/osx console, like:
`http_proxy="http://user:password@host:port" curl ifconfig.me`
and I see the IP of the host. 

Also, it works in the browser and I see the host's IP there.

This tool runs my discord, but it shows only a grey screen on start and I don't see even attempts of connections in the squid access log.
